### ISSUE TITLE
Failed to start bean 'outputBindingLifecycle'

### ISSUE THREAD

**Issue by WThamira** [kbastani/event-stream-processing-microservices#3]
I try to build this repository with mvn clean install . 

Result is 

<img width="1129" alt="screen shot 2017-03-16 at 4 01 07 pm" src="https://cloud.githubusercontent.com/assets/11591565/23992184/0245be68-0a62-11e7-97da-6a162719b081.png">

The main Caused is 

> `org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy`

Is there any initial steps to build this repository?

**Comment by naheedmk** [comment]
I am also getting same exception when I tried to deploy solution on AWS ECS docker container pointing to differe kafka host.  Log details : 2017-03-19 19:32:15,073  INFO main o.s.c.a.AnnotationUtils:1868 - Failed to introspect annotations on [class org.springframework.cloud.stream.binder.kafka.config.KafkaBinderConf
iguration]: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
2017-03-19 19:32:15,095  WARN main o.s.b.SpringApplication:91 - Error handling failed (ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events vi
a the context: org.springframework.context.annotation.AnnotationConfigApplicationContext@5ef8df1e: startup date [Thu Jan 01 00:00:00 GMT 1970]; parent: org.springframework.boot.
context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2d928643)

**Comment by naheedmk** [comment]
Got this working based on following thread
http://stackoverflow.com/questions/41986162/failed-to-start-bean-inputbindinglifecycle-when-using-spring-boot1-5-1-and-sp

Changed spring boot version in parent pom to 1.5.2.RELEASE. I think spring-integration-kafka 2.1.0 is not compatible with spring boot 1.4.4.RELEASE

**Comment by netkiller** [comment]
I am ok.

Can you remove the following dependency. and then try again.

`
               <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-monitor</artifactId>
		</dependency>
`
